config/routes.rb
Rails.application.routes.draw do
  get 'messages/index'
  get 'messages/:id', to: 'messages#show', as: 'message'
  post '/messages/search' => 'messages#search', as: 'message_search'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'messages#index'
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = CrossChainMessage.latest_messages
  end

  def show
    @message = CrossChainMessage.find(params[:id])
  end

  # @route POST `/search`
  def search
    tx_hash = params[:message][:tx_hash]

    @message = CrossChainMessage.find_by src_transaction_hash: tx_hash

    render :show
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def src_tx_link(message)
    return '-' unless message.src_tx_hash&.length&.positive?

    link_to message.src_tx_hash.truncate(16), message.src_chain.explorer_tx_url(message.src_tx_hash)
  end

  def dst_tx_link(message)
    return '-' unless message.dst_tx_hash&.length&.positive?

    link_to message.dst_tx_hash.truncate(16), message.dst_chain.explorer_tx_url(message.dst_tx_hash)
  end

  def block_number_link(message)
    return '-' unless message.block_number

    return message.block_number unless message.src_chain.explorer_block_url

    link_to message.block_number, message.src_chain.get_explorer_block_url(message.block_number)
  end
end

app/views/messages/_message_detail.html.erb
<% if message %>
  <ul class="list-group list-group-flush">
    <% message.attributes.each do |key, value| %>
      <li class="list-group-item px-0">
        <p class="h6 text-uppercase mt-1"><%= key %>: </p>
        <div class="text-break" style="font-family: 'Roboto Mono', monospace;"><%= value.nil? ? '-' : value %></div>
      </li>
    <% end %>
  </ul>
<% else %>
  <div class="alert alert-warning rounded-0" role="alert">
    No message found.
  </div>
<% end %>

app/views/messages/_message_search.html.erb
<%= turbo_frame_tag 'message_search' do %>
  <div class="row justify-content-md-center">
    <div class="mb-4 col-md-12">
      <%= form_with scope: :message, url: message_search_path, class: 'input-group' do |form| %>
        <%= form.text_field :tx_hash, type: 'text', 'aria-describedby' => 'btn-search', 'placeholder' => "Source Tx Hash", class: 'form-control border-1 bg-light border-secondary' %>
        <%= form.submit 'Search', 'id' => 'btn-search', 'class' => "btn btn-outline-secondary", data: { turbo_frame: "body" } %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/messages/_messages.html.erb
<%= turbo_stream_from "messages" %>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Time(UTC)</th>
      <th scope="col">Block</th>
      <th scope="col">From</th>
      <th scope="col">To</th>
      <th scope="col">Nonce</th>
      <th scope="col">Status</th>
      <th scope="col" class="text-end">Source Tx</th>
      <th scope="col" class="text-end">Target Tx</th>
    </tr>
  </thead>
  <tbody class="table-group-divider">
    <% messages.each do |message| %>
      <tr id="message_<%= message.id %>" class="position-relative">
        <th scope="row"><%= link_to message.id, message_path(message.id), class: "stretched-link text-decoration-none text-reset", data: { turbo: false } %></th>
        <td ><%= message.initiated_at&.strftime("%F %T") || '-' %></td>
        <td ><%= message.block_number || '-' %></td>
        <td ><%= message.src_chain.name %></td>
        <td ><%= message.dst_chain.name %></td>
        <td ><%= message.nonce %></td>
        <td ><%= message.status_bar %></td>
        <td class="text-end" style="font-family: 'Roboto Mono', monospace; font-size: 13px"><%= message.src_transaction_hash&.truncate(15) || '-' %></td>
        <td class="text-end" style="font-family: 'Roboto Mono', monospace; font-size: 13px"><%= message.dst_transaction_hash&.truncate(15) || '-' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/messages/index.html.erb
<main class="container">
  <%= render 'message_search' %>
  <%= turbo_frame_tag 'body' do %>
    <%= turbo_frame_tag 'messages' do %>
      <%= render 'messages', messages: @messages %>
    <% end %>
  <% end %>
</main>

app/views/messages/show.html.erb
<main class="container">
  <%= render 'message_search' %>
  <%= turbo_frame_tag 'body' do %>
    <%= render 'message_detail', message: @message %>
  <% end %>
</main>