config/routes.rb
Rails.application.routes.draw do
  get 'messages/index'
  get 'messages/:id', to: 'messages#show', as: 'message'
  post '/messages/search' => 'messages#search', as: 'message_search'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'messages#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Msgscan</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Major+Mono+Display&family=Roboto&family=Roboto+Mono:wght@400&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class="col-lg-9 mx-auto p-3 py-md-5">
      <header class="d-flex pb-4 mb-3">
        <a href="<%= messages_index_path %>" class="d-flex text-dark text-decoration-none mx-auto">
          <span class="fs-2" style="font-family: 'Major Mono Display', monospace;">Darwinia Cross Chain Messages</span>
        </a>
      </header>
      <%= yield %>
      <footer class="pt-3 my-5 text-muted mx-auto text-center">
        Created by the <a href="https://darwinia.network" class="text-dark text-decoration-none">Darwinia</a> team &middot; &copy; 2023
      </footer>
    </div>
  </body>
</html>